POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Growing Plants the Right Way pt. 2",
  "author": "Green Thumbs",
  "url": "plants.com",
  "likes": 8888,
  "userId": "5f41c904509a9428e3ee3703"
}